### ISSUE TITLE
No translations to Slack usersid

### ISSUE THREAD

**Issue by ASarco** [ry-itto/slack_notify_actions#5]
Hi, I've been trying to use this, but seems like the GitHub names are not being translated.

I have my translation table in a secret SLACK_USER, it looks like this:
`ASarco,U01CXS1NVDG` 
Then the title in the action is:
`BODY: '@${{ github.actor }} your recent action ${{ github.workflow }} has been built succesfully!'`
`TITLE: ':tada: Congratulations ${{ github.actor }} :tada:'`

So I assumed my name coming from github.actor should be translated to the Slack user. But the message in Slack looks like this:

> :tada: Congratulations ASarco :tada:
> @ASarco your recent action Customers Java CI with Maven has been built succesfully!

What am I doing wrong?

**Comment by ry-itto** [comment]
@ASarco 
Hi.

Did you set `SLACK_GITHUB_USER_PAIRS` environment variable?
The secret `SLACK_USER` should set to `SLACK_GITHUB_USER_PAIRS` environment variable.

Sorry for the confusing parameter names.
I hope this solves it.

**Comment by ASarco** [comment]
Yes, I did all that. This is the complete step:

    - name: Slack Notification
      with: 
        status: ${{ job.status }}
      if: success()
      uses: ry-itto/slack_notify_actions@1.0.1
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_ICON_URL: 'https://github.githubassets.com/images/modules/logos_page/Octocat.png'
        SLACK_USERNAME: 'GitHub'
        SLACK_GITHUB_USER_PAIRS: ${{ secrets.SLACK_USER }}
        TITLE: ':tada: Congratulations ${{ github.actor }} :tada:'
        BODY: '@${{ github.actor }} your recent action ${{ github.workflow }} has been built succesfully! The new version is ${{ steps.gitversion.outputs.fullSemVer }} :partyparrot:'
        COLOR: '#4D88C2'


So everything looks good. The only thing is I've seen in your tests, that there is no tests for when there are more than one line of names pairs. Maybe there's a problem with that? I have 6 names in my list.

**Comment by ry-itto** [comment]
Exactly, that is correct.

When I add test case of multiple `slackUsernames`, `npm test` was failed...

I will fix it. 🙇🏼

**Comment by ry-itto** [comment]
Hi @ASarco .

I fixed about this. Please try to use bellow 🙇🏼 

```yaml
- name: slack_notify_actions
  uses: ry-itto/slack_notify_actions@1.0.2-pre
```

I hope this release works.

**Comment by ASarco** [comment]
hi @ry-itto 
Thanks for doing a quick fix, however, it's still not quite working.
To make it work I had to change the end of line to CR only, since I see that your source code splits the list using '\n' 
It would be nice if it works for any end of line type, such as \r\n, \n or \r

Thanks.
